networks:
  ocrvnet:
    driver: bridge
services:
  azure-form-recognizer-read:
    container_name: azure-form-recognizer-layout
    environment:
    - EULA=accept
    - billing=https://ces-document-intelligence.cognitiveservices.azure.com/
    - apiKey=30bfa09ff3fe426c83e434a921277770
    image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/layout-3.1
    networks:
    - ocrvnet
    ports:
    - 5000:5000
version: '3.9'
