networks:
  ocrvnet:
    driver: bridge
services:
  azure-form-recognizer-read:
    container_name: azure-form-recognizer-read
    environment:
    - EULA=accept
    - billing=
    - apiKey=
    image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/read-3.1
  networks:
  - ocrvnet
  ports:
  - '"5000:5000"'
version: '"3.9"'
